name: Publish Package
 
on:
  push:
    branches: [master]
 
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure Git
        run: |
          git config --global user.name "holyfata"
          git config --global user.email "holyfata@qq.com"
 
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 24
 
      - name: Install Dependencies
        run: npm ci  # 使用精确依赖安装
 
      - name: Build Package
        run: npm run build  # 构建步骤
 
      # 自动更新补丁版本
      - name: Bump Version
        run: |
          npm version patch -m "Bump version to %s"
          git push origin master --follow-tags
 
      # 发布到 GitHub Packages
      - name: Publish to GitHub Packages
        if: success()
        run: |
          echo "//npm.pkg.github.com/:_authToken=${{ secrets.GH_PACKAGES_TOKEN }}" > .npmrc
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GH_PACKAGES_TOKEN }}

      # 发布到 npm 官方仓库
      - name: Publish to npm
        if: success()
        run: |
          sed -i'' 's/"name": "@holyfata\/gh-profile"/"name": "gh-profile"/g' package.json
          echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > .npmrc
          npm publish --access public --registry=https://registry.npmjs.org
          git checkout package.json
